# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iot_framework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Pods for AwsDynamoSample
    pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'

  target 'iot_frameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
